WAV bell "sfx/bell.wav" 5
WAV boom "sfx/boom.wav" 5
WAV dolphins1 "sfx/dolphins1.wav" 5
WAV dolphins2 "sfx/dolphins2.wav" 5
WAV knock1 "sfx/knock1.wav" 5
WAV knock2 "sfx/knock2.wav" 5
WAV knock3 "sfx/knock3.wav" 5
WAV neigh "sfx/neigh.wav" 5
WAV stars_bling "sfx/stars_bling.wav" 5